version: '3.9'
services:
  nginx:
    image: nginx-1
    container_name: ${NGINX_HOST}
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        ENABLED_MODULES: rtmp
    env_file: .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${RTMP_PORT}:${RTMP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rtmp.conf:/etc/nginx/conf.d/rtmp.conf
      - ./nginx/http.conf:/etc/nginx/conf.d/http.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    networks:
      - streaming-net

  wss-server:
    build:
      context: ./wss-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - nginx
    networks:
      - streaming-net
    volumes:
      - ./wss-server/temp:/app/temp

networks:
  streaming-net: