services:
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile
    buildCommand: docker build -t nginx -f ./nginx/Dockerfile ./nginx
    startCommand: nginx -g 'daemon off;'
    plan: free  # Or starter/pro as needed
    envVars:
      - key: HTTP_PORT
        value: 80
      - key: RTMP_PORT
        value: 1935
    disk:
      - name: hls
        mountPath: /tmp/hls
        sizeGB: 10  # Adjust as needed for HLS files
    healthCheckPath: /  # Checks if NGINX is up
    domains:
      - server-livestreaming.onrender.com

 # Optional custom domain

  - type: web
    name: wss-server
    env: docker
    dockerfilePath: ./wss-server/Dockerfile
    buildCommand: docker build -t wss-server -f ./wss-server/Dockerfile ./wss-server
    startCommand: node server.js
    plan: free  # Or starter/pro
    envVars:
      - key: PORT
        value: 8888
      - key: NGINX_HOST
        fromService:
          type: web
          name: nginx
          envVarKey: HOSTNAME  # Links to NGINX internally
    disk:
      - name: temp
        mountPath: /app/temp
        sizeGB: 5  # For temp files
    autoDeploy: true

networks:
  - name: streaming-net  # Internal network for services to communicate